---
- name: Deploy etherpad
  include_role:
    name: etherpad

- name: Deploy jitsi
  include_role:
    name: jitsi

- name: Deploy mattermost
  include_role:
    name: mattermost

- name: Deploy wekan
  include_role:
    name: wekan

- name: Deploy dokuwiki
  include_role:
    name: dokuwiki

- name: Deploy drawio
  include_role:
    name: drawio

- name: Deploy mozaik
  include_role:
    name: mozaik
