---
- name: Deploy drawio
  k8s:
    definition:
      kind: Deployment
      apiVersion: apps/v1
      metadata:
        name: drawio
        namespace: "{{ meta.namespace }}"
        labels:
          app: "{{drawio.application_name}}"
      spec:
        replicas: 1
        strategy:
          type: RollingUpdate
        selector:
          matchLabels:
            app: "{{drawio.application_name}}"
        template:
          metadata:
            labels:
              app: "{{drawio.application_name}}"
              name: drawio
          spec:
            containers:
            - image: quay.io/podium/drawio:latest
              imagePullPolicy: Always
              name: drawio
              ports:
              - containerPort: 8080
                protocol: TCP
              - containerPort: 8443
                protocol: TCP
              readinessProbe:
                httpGet:
                  path: /
                  port: 8080
                initialDelaySeconds: 60
                periodSeconds: 10
                timeoutSeconds: 60
              livenessProbe:
                httpGet:
                  path: /
                  port: 8080
                initialDelaySeconds: 120
                periodSeconds: 10
            terminationMessagePath: /dev/termination-log
            terminationMessagePolicy: File
          dnsPolicy: ClusterFirst
          restartPolicy: Always
          schedulerName: default-scheduler
        triggers:
        - type: ConfigChange
- name: Deploy drawio service
  k8s:
    definition:
      apiVersion: v1
      kind: Service
      metadata:
        namespace: "{{ meta.namespace }}"
        labels:
          app: "{{drawio.application_name}}"
        name: drawio
      spec:
        ports:
        - name: 8080-tcp
          port: 8080
          protocol: TCP
          targetPort: 8080
        - name: 8443-tcp
          port: 8443
          protocol: TCP
          targetPort: 8443
        selector:
          app: "{{drawio.application_name}}"
          name: drawio
      status:
        loadBalancer: {}
- name: Deploy drawio route
  k8s:
    definition:
      apiVersion: route.openshift.io/v1
      kind: Route
      metadata:
        namespace: "{{ meta.namespace }}"
        annotations:
          openshift.io/host.generated: "true"
          kubernetes.io/tls-acme: "true"
        name: drawio
      spec:
        host: "drawio-{{ meta.namespace }}.{{application_domain}}"
        port:
          targetPort: 8080
        tls:
          termination: edge
        to:
          kind: Service
          name: drawio
          weight: 100
        wildcardPolicy: None
  when: lets_encrypt
- name: Deploy drawio route
  k8s:
    definition:
      apiVersion: route.openshift.io/v1
      kind: Route
      metadata:
        namespace: "{{ meta.namespace }}"
        annotations:
          openshift.io/host.generated: "true"
        name: drawio
      spec:
        host: "drawio-{{ meta.namespace }}.{{application_domain}}"
        port:
          targetPort: 8080
        tls:
          termination: edge
        to:
          kind: Service
          name: drawio
          weight: 100
        wildcardPolicy: None
  when: not lets_encrypt
