apiVersion: template.openshift.io/v1
kind: Template
metadata:
  annotations:
    description: "Jitsi All-in-One Deployment"
  creationTimestamp: null
  name: jitsi
objects:
- apiVersion: v1
  kind: Secret
  metadata:
    name: jitsi-config
  stringData:
    JICOFO_COMPONENT_SECRET: ${JICOFO_COMPONENT_SECRET}
    JICOFO_AUTH_PASSWORD: ${JICOFO_AUTH_PASSWORD}
    JVB_AUTH_PASSWORD: ${JVB_AUTH_PASSWORD}
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      description: JVB Service
    labels:
      app: ${APPLICATION_NAME}
    name: jvb-udp
  spec:
    ports:
    - port: 30300
      protocol: UDP
      targetPort: 30300
    selector:
      app: ${APPLICATION_NAME}
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      description: Web Service
    labels:
      app: ${APPLICATION_NAME}
    name: web
  spec:
    ports:
    - name: "http"
      port: 80
      targetPort: 80
    - name: "https"
      port: 443
      targetPort: 443
    selector:
      app: ${APPLICATION_NAME}
- apiVersion: v1
  kind: Route
  metadata:
    annotations:
      template.openshift.io/expose-uri: http://{.spec.host}{.spec.path}
    name: meet
  spec:
    host: ${APPLICATION_DOMAIN}
    to:
      kind: Service
      name: web
      weight: 100
    port:
      targetPort: https
    tls:
      termination: passthrough
      insecureEdgeTerminationPolicy: None
    wildcardPolicy: None
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    labels:
      app: ${APPLICATION_NAME}
    name: ${APPLICATION_NAME}
  spec:
    replicas: 1
    strategy:
      type: Recreate
    selector:
      matchLabels:
        app: ${APPLICATION_NAME}
    template:
      metadata:
        labels:
          app: ${APPLICATION_NAME}
      spec:
        containers:
          - name: jicofo
            image: jitsi/jicofo
            imagePullPolicy: Always
            env:
              - name: XMPP_SERVER
                value: ${XMPP_SERVER}
              - name: XMPP_DOMAIN
                value: ${XMPP_DOMAIN}
              - name: XMPP_AUTH_DOMAIN
                value: ${XMPP_AUTH_DOMAIN}
              - name: XMPP_INTERNAL_MUC_DOMAIN
                value: ${XMPP_INTERNAL_MUC_DOMAIN}
              - name: JICOFO_COMPONENT_SECRET
                valueFrom:
                  secretKeyRef:
                    name: jitsi-config
                    key: JICOFO_COMPONENT_SECRET
              - name: JICOFO_AUTH_USER
                value: focus
              - name: JICOFO_AUTH_PASSWORD
                valueFrom:
                  secretKeyRef:
                    name: jitsi-config
                    key: JICOFO_AUTH_PASSWORD
              - name: TZ
                value: ${TIMEZONE}
              - name: JVB_BREWERY_MUC
                value: jvbbrewery
          - name: prosody
            image: jitsi/prosody
            imagePullPolicy: Always
            env:
              - name: XMPP_DOMAIN
                value: ${XMPP_DOMAIN}
              - name: XMPP_AUTH_DOMAIN
                value: ${XMPP_AUTH_DOMAIN}
              - name: XMPP_MUC_DOMAIN
                value: muc.meet.jitsi
              - name: XMPP_INTERNAL_MUC_DOMAIN
                value: ${XMPP_INTERNAL_MUC_DOMAIN}
              - name: JICOFO_COMPONENT_SECRET
                valueFrom:
                  secretKeyRef:
                    name: jitsi-config
                    key: JICOFO_COMPONENT_SECRET
              - name: JVB_AUTH_USER
                value: jvb
              - name: JVB_AUTH_PASSWORD
                valueFrom:
                  secretKeyRef:
                    name: jitsi-config
                    key: JVB_AUTH_PASSWORD
              - name: JICOFO_AUTH_USER
                value: focus
              - name: JICOFO_AUTH_PASSWORD
                valueFrom:
                  secretKeyRef:
                    name: jitsi-config
                    key: JICOFO_AUTH_PASSWORD
              - name: TZ
                value: America/Los_Angeles
              - name: JVB_TCP_HARVESTER_DISABLED
                value: "true"
          - name: web
            image: jitsi/web
            imagePullPolicy: Always
            env:
              - name: XMPP_SERVER
                value: ${XMPP_SERVER}
              - name: JICOFO_AUTH_USER
                value: focus
              - name: XMPP_DOMAIN
                value: ${XMPP_DOMAIN}
              - name: XMPP_AUTH_DOMAIN
                value: ${XMPP_AUTH_DOMAIN}
              - name: XMPP_INTERNAL_MUC_DOMAIN
                value: ${XMPP_INTERNAL_MUC_DOMAIN}
              - name: XMPP_BOSH_URL_BASE
                value: http://127.0.0.1:5280
              - name: XMPP_MUC_DOMAIN
                value: muc.meet.jitsi
              - name: TZ
                value: ${TIMEZONE}
              - name: JVB_TCP_HARVESTER_DISABLED
                value: "true"
          - name: jvb
            image: jitsi/jvb
            imagePullPolicy: Always
            env:
              - name: XMPP_SERVER
                value: ${XMPP_SERVER}
              - name: DOCKER_HOST_ADDRESS
                value: ${DOCKER_HOST_ADDRESS}
              - name: XMPP_DOMAIN
                value: ${XMPP_DOMAIN}
              - name: XMPP_AUTH_DOMAIN
                value: ${XMPP_AUTH_DOMAIN}
              - name: XMPP_INTERNAL_MUC_DOMAIN
                value: ${XMPP_INTERNAL_MUC_DOMAIN}
              - name: JVB_STUN_SERVERS
                value: ${JVB_STUN_SERVERS}
              - name: JICOFO_AUTH_USER
                value: focus
              - name: JVB_TCP_HARVESTER_DISABLED
                value: "true"
              - name: JVB_AUTH_USER
                value: jvb
              - name: JVB_PORT
                value: "30300"
              - name: JVB_AUTH_PASSWORD
                valueFrom:
                  secretKeyRef:
                    name: jitsi-config
                    key: JVB_AUTH_PASSWORD
              - name: JICOFO_AUTH_PASSWORD
                valueFrom:
                  secretKeyRef:
                    name: jitsi-config
                    key: JICOFO_AUTH_PASSWORD
              - name: JVB_BREWERY_MUC
                value: jvbbrewery
              - name: TZ
                value: ${TIMEZONE}
parameters:
  - name: APPLICATION_NAME
    displayName: Application Name
    description: the name and label for all components
    value: jitsi
    required: true 
  - name: APPLICATION_DOMAIN
    displayName: Application Domain
    description: Application domain name used in route to service
  - name: TIMEZONE
    displayName: Timezone
    description: The default timezone
    value: America/Los_Angeles
    required: true
  - name: JVB_STUN_SERVERS
    displayName: JVB Stun Servers
    description: Comma separated list of STUN servers (optional)
    value: 
  - name: DOCKER_HOST_ADDRESS
    displayName: Docker Host IP
    description: IP or Hostname where Pod is running
    value: localhost
    required: true 
  - name: XMPP_SERVER
    displayName: XMPP Server
    description: XMPP Server
    value: localhost
    required: true 
  - name: XMPP_DOMAIN
    displayName: XMPP Domain
    description: XMPP Domain
    value: meet.jitsi
    required: true 
  - name: XMPP_AUTH_DOMAIN
    displayName: XMPP Auth Domain
    description: XMPP Auth Domain
    value: auth.meet.jitsi
    required: true 
  - name: XMPP_INTERNAL_MUC_DOMAIN
    displayName: XMPP Internal Muc Domain
    description: XMPP Internal Muc Domain
    value: internal-muc.meet.jitsi
    required: true 
