---
- name: Set Dashboard Parameters
  set_fact:
    meeting_1_name: "{{ mozaik.custom_meeting_1_name if mozaik.custom_meeting_1_name is defined else 'Townhall' }}"
    meeting_1_url: "{{ mozaik.custom_meeting_1_url if mozaik.custom_meeting_1_url is defined else 'https://meet-{{ meta.namespace }}.{{ application_domain }}/Townhall' }}"
    meeting_1_image_url: "{{ mozaik.custom_meeting_1_image_url if mozaik.custom_meeting_1_image_url is defined else 'https://cdn.pixabay.com/photo/2013/02/20/01/04/meeting-83519__340.jpg' }}"
    meeting_2_name: "{{ mozaik.custom_meeting_2_name if mozaik.custom_meeting_2_name is defined else 'Roundtable' }}"
    meeting_2_url: "{{ mozaik.custom_meeting_2_name if mozaik.custom_meeting_2_name is defined else 'https://meet-{{ meta.namespace }}.{{ application_domain }}/Roundtable' }}"
    meeting_2_image_url: "{{ mozaik.custom_meeting_2_image_url if mozaik.custom_meeting_2_image_url is defined else 'https://cdn.pixabay.com/photo/2015/07/02/09/52/interior-design-828545__340.jpg' }}"
    meeting_3_name: "{{ mozaik.custom_meeting_3_name if mozaik.custom_meeting_3_name is defined else 'Lobby' }}"
    meeting_3_url: "{{ mozaik.custom_meeting_3_url if mozaik.custom_meeting_3_url is defined else 'https://meet-{{ meta.namespace }}.{{ application_domain }}/Lobby' }}"
    meeting_3_image_url: "{{ mozaik.custom_meeting_3_image_url if mozaik.custom_meeting_3_image_url is defined else 'https://cdn.pixabay.com/photo/2019/11/29/08/34/space-4660847__340.jpg' }}"
    wiki_name: "{{ mozaik.custom_wiki_url if mozaik.custom_wiki_url is defined else 'Wiki' }}"
    wiki_url: "{{ mozaik.custom_wiki_name if mozaik.custom_wiki_name is defined else 'https://dokuwiki-{{ meta.namespace }}.{{ application_domain }}' }}"
    wiki_image_url: "{{ mozaik.custom_wiki_image_url if mozaik.custom_wiki_image_url is defined else 'https://www.dokuwiki.org/_media/wiki:dokuwiki-128.png' }}"
    draw_name: "{{ mozaik.custom_draw_name if mozaik.custom_draw_name is defined else 'Draw.io' }}"
    draw_url: "{{ mozaik.custom_draw_url if mozaik.custom_draw_url is defined else 'https://drawio-{{ meta.namespace }}.{{ application_domain }}' }}"
    draw_image_url: "{{ mozaik.custom_draw_image_url if mozaik.custom_draw_image_url is defined else 'https://cdn.worldvectorlogo.com/logos/draw-io.svg' }}"
    kanban_name: "{{ mozaik.custom_kanban_name if mozaik.custom_kanban_name is defined else 'Wekan' }}"
    kanban_url: "{{ mozaik.custom_kanban_url if mozaik.custom_kanban_url is defined else 'https://wekan-{{ meta.namespace }}.{{ application_domain }}' }}"
    kanban_image_url: "{{ mozaik.custom_kanban_image_url if mozaik.custom_kanban_image_url is defined else 'https://wekan.github.io/wekan-logo.svg' }}"
    mindmaps_name: "{{ mozaik.custom_mindmaps_name if mozaik.custom_mindmaps_name is defined else 'Mindmaps' }}"
    mindmaps_url: "{{ mozaik.custom_mindmaps_url if mozaik.custom_mindmaps_url is defined else 'https://mindmaps-{{ meta.namespace }}.{{ application_domain }}' }}"
    mindmaps_image_url: "{{ mozaik.custom_mindmaps_image_url if mozaik.custom_mindmaps_image_url is defined else 'https://raw.githubusercontent.com/sa-mw-dach/podium/master/docs/images/mindmap.png' }}"
    chat_name: "{{ mozaik.custom_chat_name if mozaik.custom_chat_name is defined else 'Mattermost Chat' }}"
    chat_url: "{{ mozaik.custom_chat_url if mozaik.custom_chat_url is defined else 'https://chat-{{ meta.namespace }}.{{ application_domain }}' }}"
    chat_image_url: "{{ mozaik.custom_chat_image_url if mozaik.custom_chat_image_url is defined else 'https://cdn.freebiesupply.com/logos/large/2x/mattermost-logo-png-transparent.png' }}"

- name: Set Etherpad/Etherdraw Dashboard Links
  set_fact:
    etherpad_1_name: "{{ meeting_1_name }} Agenda and Notes"
    etherpad_1_url: "https://etherpad-{{ meta.namespace }}.{{ application_domain }}/p/{{ meeting_1_name }}"
    etherpad_2_name: "{{ meeting_2_name }} Agenda and Notes"
    etherpad_2_url: "https://etherpad-{{ meta.namespace }}.{{ application_domain }}/p/{{ meeting_2_name }}"
    etherpad_3_name: "{{ meeting_3_name }} Agenda and Notes"
    etherpad_3_url: "https://etherpad-{{ meta.namespace }}.{{ application_domain }}/p/{{ meeting_3_name }}"
    etherdraw_1_name: "{{ meeting_1_name }} Whiteboard"
    etherdraw_1_url: "https://etherdraw-{{ meta.namespace }}.{{ application_domain }}/d/{{ meeting_1_name }}"
    etherdraw_2_name: "{{ meeting_2_name }} Whiteboard"
    etherdraw_2_url: "https://etherdraw-{{ meta.namespace }}.{{ application_domain }}/d/{{ meeting_2_name }}"
    etherdraw_3_name: "{{ meeting_3_name }} Whiteboard"
    etherdraw_3_url: "https://etherdraw-{{ meta.namespace }}.{{ application_domain }}/d/{{ meeting_3_name }}"

- name: Deploy Mozaik ConfigMap
  k8s:
    definition:
      apiVersion: v1
      kind: ConfigMap
      metadata:
        name: mozaik-config
        namespace: "{{ meta.namespace }}"
      data:
        podium-conf: |
          // Load environment variables from .env file if available
          require('dotenv').load();

          var config = {
              env:  'prod',

              host: '0.0.0.0',
              port: process.env.PORT || 8080,

              // Available themes:
              // + bordeau
              // + harlequin
              // + light-grey
              // + light-yellow
              // + night-blue
              // + snow
              // + yellow
              theme: 'harlequin',

              // clients configs
              api: {
                  github: {
                      baseUrl: 'https://api.github.com',
                      token: ''
                  }
              },

              // define the interval used by Mozaïk Bus to call registered APIs
              apisPollInterval: 15000,
              dashboards: [

                  {
                      // 4 x 3 dashboard
                      columns: 4,
                      rows:    3,
                      widgets: [
                          {
                              type: 'github.user_badge',
                              user: 'sa-mw-dach',
                              columns: 1, rows: 1,
                              x: 0, y: 0
                          },
                          {
                              type: 'github.repository_contributors_stats',
                              repository: 'sa-mw-dach/podium',
                              columns: 1, rows: 1,
                              x: 2, y: 0
                          },
                          {
                              type: 'mozaik.inspector',
                              columns: 1, rows: 1,
                              x: 1, y: 0
                          },
                          {
                              type: 'embed.markup',
                              title: 'Conference Center',
                              content: '<center><a href="{{ meeting_1_url }}" target="_blank" rel="noreferrer noopener"><img src="{{ meeting_1_image_url }}" alt="{{ meeting_1_name }}" width="300" height="200"></a>  <a href="{{ meeting_2_url }}" target="_blank" rel="noreferrer noopener"><img src="{{ meeting_2_image_url }}" alt="{{ meeting_2_name }}" width="300" height="200"></a>  <a href="{{ meeting_3_url }}" target="_blank" rel="noreferrer noopener"><img src="{{ meeting_3_image_url }}" alt="{{ meeting_3_name }}" width="300" height="200"></a></center>',
                              columns: 2, rows: 1,
                              x: 1, y: 1
                          },
                          {
                              type: 'time.clock',
                              columns: 1, rows: 1,
                              x: 3, y: 0
                          },
                          {
                              type: 'embed.markup',
                              title: 'Knowledge Base',
                              content: '<center><a href="{{ wiki_url }}" target="_tab" rel="noreferrer noopener"><img src="{{ wiki_image_url }}" alt="{{ wiki_name }}" width="200" height="120"></a> <a href="https://openpracticelibrary.com/" target="_tab" rel="noreferrer noopener"><img src="https://d33wubrfki0l68.cloudfront.net/337d8258554af2343978fdbcd7e854298ab8062c/e7414/images/logo.svg" alt="Open Practice Library" width="200" height="120"></a></center>',
                              columns: 1, rows: 1,
                              x: 0, y: 1
                          },
                          {
                              type: 'embed.markup',
                              title: 'Collaboration Boards',
                              content: '<a href="https://etherpad-{{ meta.namespace }}.{{ application_domain }}/" target="_tab" rel="noreferrer noopener"><img src="https://raw.githubusercontent.com/sa-mw-dach/podium/master/docs/images/etherpad-300x600.png" alt="Etherpad" width="300" height="150"></a>  <ul> <li><a href="{{ etherpad_1_url }}" target="_tab" rel="noreferrer noopener">{{ etherpad_1_name }}</a></li> <li><a href="{{ etherpad_2_url }}" target="_tab" rel="noreferrer noopener">{{ etherpad_2_name }}</a></li> <li><a href="{{ etherpad_3_url }}" target="_tab" rel="noreferrer noopener">{{ etherpad_3_name }}</a></li> <li><a href="https://etherpad-{{ meta.namespace }}.{{ application_domain }}/p/ToDo" target="_tab" rel="noreferrer noopener">ToDo Pad</a></li></ul><p><a href="https://etherdraw-{{ meta.namespace }}.{{ application_domain }}/" target="_tab" rel="noreferrer noopener"><img src="https://raw.githubusercontent.com/sa-mw-dach/podium/master/docs/images/etherdraw-300x600.png" alt="Etherdraw" width="300" height="150"></a>  <ul> <li><a href="{{ etherdraw_1_url }}" target="_tab" rel="noreferrer noopener">{{ etherdraw_1_name }}</a></li> <li><a href="{{ etherdraw_2_url }}" target="_tab" rel="noreferrer noopener">{{ etherdraw_2_name }}</a></li> <li><a href="{{ etherdraw_3_url }}" target="_tab" rel="noreferrer noopener">{{ etherdraw_3_name }}</a></li> <li><a href="https://etherdraw-{{ meta.namespace }}.{{ application_domain }}/d/Draft" target="_tab" rel="noreferrer noopener">Draft Whiteboard</a></li></ul>',
                              columns: 1, rows: 2,
                              x: 3, y: 1
                          },
                          {
                              type: 'embed.markup',
                              title: 'Productivity Tools',
                              content: '<center><a href="{{ draw_url }}" target="_tab" rel="noreferrer noopener"><img src="{{ draw_image_url }}" alt="{{ draw_name }}" width="300" height="200"></a><a href="{{ kanban_url }}" target="_tab" rel="noreferrer noopener"><img src="{{ kanban_image_url }}" alt="{{ kanban_name }}" width="300" height="200"></a><a href="{{ mindmaps_url }}" target="_tab" rel="noreferrer noopener"><img src="{{ mindmaps_image_url }}" alt="{{ mindmaps_name }}" width="300" height="200"></center>',
                              columns: 2, rows: 1,
                              x: 1, y: 2
                          },
                          {
                              type: 'embed.markup',
                              title: 'Chat',
                              content: '<center><a href="{{ chat_url }}" target="_blank" rel="noreferrer noopener"><img src="{{ chat_image_url }}" alt="{{ chat_name }}" width="300" height="200"></a></center>',
                              columns: 1, rows: 1,
                              x: 0, y: 2
                          }
                      ]
                  },

              ]
          };

          module.exports = config;
- name: Deploy podium dashboard
  k8s:
    definition:
      kind: Deployment
      apiVersion: apps/v1
      metadata:
        name: mozaik
        namespace: "{{ meta.namespace }}"
        labels:
          app: "{{mozaik.application_name}}"
      spec:
        replicas: 1
        strategy:
          type: RollingUpdate
        selector:
          matchLabels:
            app: "{{mozaik.application_name}}"
        template:
          metadata:
            labels:
              app: "{{mozaik.application_name}}"
              name: mozaik
          spec:
            containers:
            - image: quay.io/podium/mozaik:latest
              imagePullPolicy: Always
              name: mozaik
              ports:
              - containerPort: 8080
                protocol: TCP
              volumeMounts:
              - mountPath: /opt/app-root/src/config.js
                name: dashboard-config
                subPath: config.js
              readinessProbe:
                httpGet:
                  path: /
                  port: 8080
                initialDelaySeconds: 5
                periodSeconds: 3
                timeoutSeconds: 60
              livenessProbe:
                httpGet:
                  path: /
                  port: 8080
                initialDelaySeconds: 10
                periodSeconds: 3
            volumes:
            - configMap:
                defaultMode: 420
                items:
                - key: podium-conf
                  path: config.js
                name: mozaik-config
              name: dashboard-config
            restartPolicy: Always
        triggers:
        - type: ConfigChange
      status: {}
- name: Deploy moziak service
  k8s:
    definition:
      apiVersion: v1
      kind: Service
      metadata:
        namespace: "{{ meta.namespace }}"
        labels:
          app: "{{mozaik.application_name}}"
        name: mozaik
      spec:
        ports:
        - port: 8080
          protocol: TCP
          targetPort: 8080
        selector:
          app: "{{mozaik.application_name}}"
          name: mozaik
        sessionAffinity: None
        type: ClusterIP
      status:
        loadBalancer: {}
- name: Deploy moziak route
  k8s:
    definition:
      apiVersion: route.openshift.io/v1
      kind: Route
      metadata:
        namespace: "{{ meta.namespace }}"
        annotations:
          openshift.io/host.generated: "true"
        name: mozaik
      spec:
        host: "podium-{{ meta.namespace }}.{{application_domain}}"
        to:
          kind: Service
          name: mozaik
          weight: 100
        port:
          targetPort: 8080
        wildcardPolicy: None
