apiVersion: podium.com/v1alpha1
kind: Podium
metadata:
  name: mypodium
spec:
  application_domain: <apps wildcard domain>
  namespace: <namespace>
  jvb_node_port: 30000
  etherpad:
    enable: true
    application_name: etherpad
    default_title: "Welcome to Etherpad"
    default_text: "Etherpad is a real-time text editor"
  jitsi:
    enable: true
    application_name: jitsi
    jicofo_component_secret: s3cr3t
    jicofo_auth_user: focus
    jicofo_auth_password: <password>
    jvb_auth_user: jvb
    jvb_auth_password: <password>
    jvb_brewery_muc: jvbbrewery
    jvb_tcp_harvester_disabled: 'true'
    jvb_enable_apis: rest
    jvb_stun_servers: meet-jit-si-turnrelay.jitsi.net:443
    timezone: Europe/Berlin
    jvb_node_selector: jvb
  mattermost:
    enable: true
    application_name: mattermost-team-edition
    mysql_user_password: <password>
    mysql_root_password: <password>
  wekan:
    enable: true
    application_name: wekan
    mongo_database_name: wekan
    mongo_database_user: wekan
    mongo_database_password: <password>
    mongo_admin_password: <password>
  drawio:
    enable: true
    application_name: drawio
  dokuwiki:
    enable: true
    application_name: dokuwiki
  mozaik:
    enable: true
    application_name: mozaik
