apiVersion: template.openshift.io/v1
kind: Template
metadata:
  annotations:
    description: "Mozaik ConfigMap for Podium App"
  creationTimestamp: null
  name: mozaik-config
objects:
- apiVersion: v1
  kind: ConfigMap
  metadata:
    name: mozaik-config
  data:
   podium-conf: |
      // Load environment variables from .env file if available
      require('dotenv').load();
  
      var config = {
          env:  'prod',
  
          host: '0.0.0.0',
          port: process.env.PORT || 8080,
  
          // Available themes:
          // + bordeau
          // + harlequin
          // + light-grey
          // + light-yellow
          // + night-blue
          // + snow
          // + yellow
          theme: 'harlequin',
  
          // clients configs
          api: {
              github: {
                  baseUrl: '${GIT_API}',
                  token: '${GIT_TOKEN}'
              }
          },
  
          // define the interval used by Mozaïk Bus to call registered APIs
          apisPollInterval: 15000,
  
          dashboards: [
  
              {
                  // 4 x 3 dashboard
                  columns: 4,
                  rows:    3,
                  widgets: [
                      {
                          type: 'github.user_badge',
                          user: 'sa-mw-dach',
                          columns: 1, rows: 1,
                          x: 0, y: 0
                      },
                      {
                          type: 'github.repository_contributors_stats',
                          repository: 'sa-mw-dach/podium',
                          columns: 1, rows: 1,
                          x: 2, y: 0
                      },
                      {
                          type: 'mozaik.inspector',
                          columns: 1, rows: 1,
                          x: 1, y: 0
                      },
                      {
                          type: 'embed.markup',
                          title: 'Conference Center',
                          content: '<center><a href="https://meet-${NAMESPACE}${GUID}.${APPLICATION_DOMAIN}/Plenum" target="_blank" rel="noreferrer noopener"><img src="https://cdn.pixabay.com/photo/2013/02/20/01/04/meeting-83519__340.jpg" alt="Main Podium" width="300" height="200"></a>  <a href="https://meet-${NAMESPACE}${GUID}.${APPLICATION_DOMAIN}/Roundtable" target="_blank" rel="noreferrer noopener"><img src="https://cdn.pixabay.com/photo/2015/07/02/09/52/interior-design-828545__340.jpg" alt="Roundtable" width="300" height="200"></a>  <a href="https://meet-${NAMESPACE}${GUID}.${APPLICATION_DOMAIN}/Lobby" target="_blank" rel="noreferrer noopener"><img src="https://cdn.pixabay.com/photo/2019/11/29/08/34/space-4660847__340.jpg" alt="Lobby" width="300" height="200"></a></center>',
                          columns: 2, rows: 1,
                          x: 1, y: 1
                      },
                      {
                          type: 'time.clock',
                          columns: 1, rows: 1,
                          x: 3, y: 0
                      },
                      {
                          type: 'embed.markup',
                          title: 'Knowledge Base',
                          content: '<center><a href="https://dokuwiki-${NAMESPACE}${GUID}.${APPLICATION_DOMAIN}/" target="_tab" rel="noreferrer noopener"><img src="https://www.dokuwiki.org/_media/wiki:dokuwiki-128.png" alt="Podium Wiki" width="200" height="120"></a> <a href="https://openpracticelibrary.com/" target="_tab" rel="noreferrer noopener"><img src="https://d33wubrfki0l68.cloudfront.net/337d8258554af2343978fdbcd7e854298ab8062c/e7414/images/logo.svg" alt="Open Practice Library" width="200" height="120"></a></center>',
                          columns: 1, rows: 1,
                          x: 0, y: 1
                      },
                      {
                          type: 'embed.markup',
                          title: 'Sketch Boards',
                          content: '<a href="https://etherpad-${NAMESPACE}${GUID}.${APPLICATION_DOMAIN}/" target="_tab" rel="noreferrer noopener"><img src="https://factomedia.files.wordpress.com/2016/12/n4.jpg" alt="Etherpad" width="300" height="200"></a>  <ul> <li><a href="https://etherpad-${NAMESPACE}${GUID}.${APPLICATION_DOMAIN}/p/Podium" target="_tab" rel="noreferrer noopener">Podium Agenda and Notes</a></li> <li><a href="https://etherpad-${NAMESPACE}${GUID}.${APPLICATION_DOMAIN}/p/Roundtable" target="_tab" rel="noreferrer noopener">Roundtable Agenda and Notes</a></li> <li><a href="https://etherpad-${NAMESPACE}${GUID}.${APPLICATION_DOMAIN}/p/Lobby" target="_tab" rel="noreferrer noopener">Lobby Agenda and Notes</a></li> <li><a href="https://etherpad-${NAMESPACE}${GUID}.${APPLICATION_DOMAIN}/p/Draft" target="_tab" rel="noreferrer noopener">Draft Pad</a></li> <li><a href="https://etherpad-${NAMESPACE}${GUID}.${APPLICATION_DOMAIN}/p/ToDo" target="_tab" rel="noreferrer noopener">ToDo Pad</a></li></ul>',
                          columns: 1, rows: 2,
                          x: 3, y: 1
                      },
                      {
                          type: 'embed.markup',
                          title: 'Productivity Tools',
                          content: '<center><a href="https://drawio-${NAMESPACE}${GUID}.${APPLICATION_DOMAIN}/" target="_tab" rel="noreferrer noopener"><img src="https://cdn.worldvectorlogo.com/logos/draw-io.svg" alt="Podium Draw.io" width="300" height="200"></a><a href="https://wekan-${NAMESPACE}${GUID}.${APPLICATION_DOMAIN}/" target="_tab" rel="noreferrer noopener"><img src="https://wekan.github.io/wekan-logo.svg" alt="Podium Kanban" width="300" height="200"></a></center>',
                          columns: 2, rows: 1,
                          x: 1, y: 2
                      },
                      {
                          type: 'embed.markup',
                          title: 'Chat',
                          content: '<center><a href="https://chat-mattermost.${APPLICATION_DOMAIN}" target="_blank" rel="noreferrer noopener"><img src="https://cdn.freebiesupply.com/logos/large/2x/mattermost-logo-png-transparent.png" alt="Mattermost Chat" width="300" height="200"></a></center>',
                          columns: 1, rows: 1,
                          x: 0, y: 2
                      }
                  ]
              },
  
          ]
      };
  
      module.exports = config;
parameters:
  - name: NAMESPACE
    displayName: Application Name
    description: the name and label for all components
    value: podium
    required: true 
  - name: GUID
    displayName: Application GUID
    description: the GUID name component for the individual instance in a series of application deployments, typically a dash followed by a 4 character string like -f3ax
    required: false
  - name: APPLICATION_DOMAIN
    displayName: Application Domain
    description: Application domain name used in route to service
    value: apps.cloud.example.com
    required: true
  - name: GIT_URL
    displayName: Git URL
    description: Git repository with DokuWiki content
    value: https://github.com/sa-mw-dach/podium.git
    required: true
  - name: GIT_API
    displayName: Git API
    description: API endpoint for Git interaction
    value: https://api.github.com
    required: false
  - name: GIT_TOKEN
    displayName: Git Token
    description: Token for authenticated Git interaction
    required: false
