---
- name: Deploy etherpad
  k8s:
    definition:
      kind: Deployment
      apiVersion: apps/v1
      metadata:
        name: etherpad
        namespace: "{{ namespace }}"
        labels:
          app: "{{etherpad.application_name}}"
      spec:
        replicas: 1
        strategy:
          type: RollingUpdate
        selector:
          matchLabels:
            app: "{{etherpad.application_name}}"
        template:
          metadata:
            labels:
              app: "{{etherpad.application_name}}"
              name: etherpad
          spec:
            containers:
            - env:
              - name: TITLE
                value: "{{etherpad.default_text}}"
              - name: DEFAULT_PAD_TEXT
                value: "{{etherpad.default_text}}"
              image: etherpad/etherpad
              imagePullPolicy: Always
              name: etherpad
              readinessProbe:
                httpGet:
                  path: /
                  port: 9001
                initialDelaySeconds: 60
                periodSeconds: 10
                timeoutSeconds: 60
              livenessProbe:
                httpGet:
                  path: /
                  port: 9001
                initialDelaySeconds: 120
                periodSeconds: 10
              ports:
              - containerPort: 9001
            restartPolicy: Always
        triggers:
        - type: ConfigChange
- name: Deploy etherpad service
  k8s:
    definition:
      apiVersion: v1
      kind: Service
      metadata:
        namespace: "{{ namespace }}"
        labels:
          app: "{{etherpad.application_name}}"
        name: etherpad
      spec:
        ports:
        - port: 9001
          targetPort: 9001
        selector:
          app: "{{etherpad.application_name}}"
          name: etherpad
      status:
        loadBalancer: {}
- name: Deploy etherpad route
  k8s:
    definition:
      apiVersion: route.openshift.io/v1
      kind: Route
      metadata:
        namespace: "{{ namespace }}"
        annotations:
          openshift.io/host.generated: "true"
          kubernetes.io/tls-acme: "true"
        name: etherpad
      spec:
        host: "etherpad-{{namespace}}.{{application_domain}}"
        port:
          targetPort: 9001
        tls:
          termination: edge
        to:
          kind: Service
          name: etherpad
          weight: 100
        wildcardPolicy: None
